### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by willdashwood** [openprovider/Openprovider-WHMCS-domains#239]
We upgraded to PHP 7.4 from 7.3 last week and since then we've had this error on cron. It might just be coincidence.

`  7/34 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  20% 5 mins/28 mins 94.5 MiBError: Object of class OpenProvider\API\Domain could not be converted to string in /var/www/webroot/ROOT/billing/modules/registrars/openprovider/Controllers/System/RenewDomainController.php:97

#0 /var/www/webroot/ROOT/billing/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(47): OpenProvider\WhmcsRegistrar\Controllers\System\RenewDomainController->renew()
#1 /var/www/webroot/ROOT/billing/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(54): WeDevelopCoffee\wPower\Core\Instance->execute()
#2 /var/www/webroot/ROOT/billing/modules/registrars/openprovider/openprovider.php(351): WeDevelopCoffee\wPower\Core\Launch->output()
#3 /var/www/webroot/ROOT/billing/modules/registrars/openprovider/openprovider.php(189): openprovider_registrar_launch_decorator()
#4 /var/www/webroot/ROOT/billing/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): openprovider_RenewDomain()
#5 /var/www/webroot/ROOT/billing/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call()
#6 /var/www/webroot/ROOT/billing/includes/registrarfunctions.php(0): WHMCS\Module\Registrar->call()
#7 /var/www/webroot/ROOT/billing/includes/invoicefunctions.php(0): RegRenewDomain()
#8 /var/www/webroot/ROOT/billing/includes/invoicefunctions.php(0): makeDomainPayment()
#9 /var/www/webroot/ROOT/billing/vendor/whmcs/whmcs-foundation/lib/Billing/Invoice.php(0): processPaidInvoice()
#10 /var/www/webroot/ROOT/billing/includes/ccfunctions.php(0): WHMCS\Billing\Invoice->addPayment()
#11 /var/www/webroot/ROOT/billing/includes/ccfunctions.php(0): captureCCPayment()
#12 /var/www/webroot/ROOT/billing/vendor/whmcs/whmcs-foundation/lib/Cron/Task/ProcessCreditCardPayments.php(0): ccProcessing()
#13 /var/www/webroot/ROOT/billing/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Cron\Task\ProcessCreditCardPayments->__invoke()
#14 /var/www/webroot/ROOT/billing/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute()
#15 /var/www/webroot/ROOT/billing/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run()
#16 /var/www/webroot/ROOT/billing/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection()
#17 /var/www/webroot/ROOT/billing/vendor/symfony/console/Command/Command.php(255): WHMCS\Cron\Console\Command\AbstractCronCommand->execute()
#18 /var/www/webroot/ROOT/billing/vendor/symfony/console/Application.php(912): Symfony\Component\Console\Command\Command->run()
#19 /var/www/webroot/ROOT/billing/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#20 /var/www/webroot/ROOT/billing/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#21 /var/www/webroot/ROOT/billing/crons/cron.php(0): Symfony\Component\Console\Application->run()
#22 {main}`

**Comment by willdashwood** [comment]
Sorry, found this was actually to do with debug code I'd added earlier.
