### ISSUE TITLE
[BUG] DEVELOP MORE COFFEE - OpenProvider Module is broken with 

### ISSUE THREAD

**Issue by maverick85** [openprovider/Openprovider-WHMCS-domains#258]
**Describe the bug**
The 'wedevelopcoffee' module used by OpenProvider is completely killing OpenProvider WHMCS.
It is unbelievable that so long after the PHP8.1 support has been released, OP isn't already prepared for this.
Whenever a customer tries to register a domain, we get this error.

**To Reproduce**
1. Have WHMCS with PHP8.1;
2. Be using OpenProvider;
3. Have someone try to register a domain with you;
4. Try to accept the order

```
TypeError: Cannot access offset of type string on string in /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Domain/AdditionalFields.php:97
Stack trace:
#0 /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/src/AdditionalFields.php(93): WeDevelopCoffee\wPower\Domain\AdditionalFields->getFilteredAdditionalFields()
#1 /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/src/AdditionalFields.php(106): OpenProvider\WhmcsRegistrar\src\AdditionalFields->get()
#2 /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/Controllers/System/DomainController.php(112): OpenProvider\WhmcsRegistrar\src\AdditionalFields->processAdditionalFields()
#3 /var/www/sites/proj1ty4/public_html/prod/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(47): OpenProvider\WhmcsRegistrar\Controllers\System\DomainController->register()
#4 /var/www/sites/proj1ty4/public_html/prod/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(54): WeDevelopCoffee\wPower\Core\Instance->execute()
#5 /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/openprovider.php(351): WeDevelopCoffee\wPower\Core\Launch->output()
#6 /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/openprovider.php(52): openprovider_registrar_launch_decorator()
#7 [internal function]: openprovider_RegisterDomain()
#8 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func()
#9 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call()
#10 /var/www/sites/proj1ty4/public_html/prod/includes/registrarfunctions.php(0): WHMCS\Module\Registrar->call()
#11 /var/www/sites/proj1ty4/public_html/prod/includes/orderfunctions.php(0): RegRegisterDomain()
#12 /var/www/sites/proj1ty4/public_html/prod/op/orders.php(0): acceptOrder()
#13 {main}
```

**Expected behavior**
Order successfully accepted.

**Screenshots**

**Server info:**
 - Distro: AlmaLinux 9
 - PHP: 8.1
 - Web server: httpd

**Additional context**
This is another issue related to this:
https://github.com/openprovider/Openprovider-WHMCS-domains/issues/252

The above mentioned issue has been reported in the 12th of December. I AM SORRY BUT IT'S ABSOLUTELY INADMISSIBLE THAT THIS HASN'T BEEN FIXED YET.
Waiting for a USER CONTRIBUTION is no excuse for it not having been solved yet.

It is not the first time we've had issues on our business because of outdated code and 3rd party libraries OpenProvider uses. I have incoming new year customers trying to register domains AND I CAN'T ACCEPT THE ORDER.
DOES OPENPROVIDER HAVE DEVELOPERS??? ARE WE WAITING FOR **ONE** 'WHMCS GUY' WHO APPARENTLY IS NEVER THERE?

**Comment by maverick85** [comment]
Initial errors reported via direct ticket to OpenProvider support.
Received an email yesterday saying my ticket was marked as "solved".

Waiting for resolution, got none. Apparently there isn't even enough honestly to keep a ticket open while the situation is being treated. Just close the tickets and take a ... on the customer.

**Comment by lonyai** [comment]
I have a similar php-8.1 incompatibility with the domain sync. I use master branch.

Error: Call to a member function find() on null in /home/u174854315/domains/cdncli.com/public_html/modules/registrars/openprovider/Controllers/System/DomainSyncController.php:69
Stack trace:
#0 /home/u174854315/domains/cdncli.com/public_html/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(47): OpenProvider\WhmcsRegistrar\Controllers\System\DomainSyncController->sync()
#1 /home/u174854315/domains/cdncli.com/public_html/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(54): WeDevelopCoffee\wPower\Core\Instance->execute()
#2 /home/u174854315/domains/cdncli.com/public_html/modules/registrars/openprovider/openprovider.php(354): WeDevelopCoffee\wPower\Core\Launch->output()
#3 /home/u174854315/domains/cdncli.com/public_html/modules/registrars/openprovider/openprovider.php(273): openprovider_registrar_launch_decorator()
#4 [internal function]: openprovider_Sync()
#5 /home/u174854315/domains/cdncli.com/public_html/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func()
#6 /home/u174854315/domains/cdncli.com/public_html/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call()
#7 /home/u174854315/domains/cdncli.com/public_html/includes/registrarfunctions.php(0): WHMCS\Module\Registrar->call()
#8 /home/u174854315/domains/cdncli.com/public_html/includes/registrarfunctions.php(0): RegCallFunction()
#9 /home/u174854315/domains/cdncli.com/public_html/adminq/clientsdomains.php(0): RegCustomFunction()
#10 {main}

**Comment by spylex** [comment]
I'm having both of the issues here, can't register, can't sync, same logs. What is going on... Is downgrading PHP version the solution?

**Comment by maverick85** [comment]
> I'm having both of the issues here, can't register, can't sync, same logs. What is going on... Is downgrading PHP version the solution? I also can't download the support files from the addon section as it has the same coffee error...

After months long struggle seems like OP is finally getting somewhere. They've sent a couple of fixes to test.
Maybe very soon this will be over.

Funny thing is I sent them a video downloading WHMCS full from WHMCS site, copied `configuration.php` over, installed the module, and the errors show immediately. However, they say they can't replicate. Figure that out.

But yeah, it's being worked on.

**Comment by spylex** [comment]
There's been a change, and i've copied over, but still...

**Comment by spylex** [comment]
After copying in @wyler-m updates from 4 days ago, i am getting domain sync again. However, 2 renewals were missed completely so i had to manually restore them - frustrating...

I still can't generate error or activity reports.

**Comment by sapillai** [comment]
@spylex 

If you are still having the error "**_Cannot access offset of type string on string_**" with **AdditionalFields.php** while registering domains, please try the fix mentioned [here](https://github.com/openprovider/Openprovider-WHMCS-domains/issues/252#issuecomment-1413302182).

**Comment by spylex** [comment]
I have tried that - errors are not appearing.

However, i am still getting domain renewals being missed. This is just not workable.

**Comment by sapillai** [comment]
@spylex

Please create [a new issue](https://github.com/openprovider/Openprovider-WHMCS-domains/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D) if you are experiencing a different issue from the one reported in the initial post (domain registration error) and include problem description, steps to reproduce, server information and WHMCS details.

**Comment by sapillai** [comment]
Hi,

I'm glad to share that a proper official fix has been added for error "Cannot access offset of type string on string" with 'AdditionalFields.php' in the latest version of the module - [version 5.8.0](https://github.com/openprovider/Openprovider-WHMCS-domains/releases/tag/v5.8.0).
