### ISSUE TITLE
[BUG] WHMCS & PHP8 

### ISSUE THREAD

**Issue by maverick85** [openprovider/Openprovider-WHMCS-domains#265]
**Describe the bug**
This is another bug that stems from the various issues that popped with the PHP8 upgrade.

What happens now is simple: The OpenProvider module does not renew domains, customers pay the renewal invoice and it gives a PHP Fatal error while renewing.
If I accept the order in the backoffice, it fails the same.

Some other bugs on this issue:
https://github.com/openprovider/Openprovider-WHMCS-domains/issues/252
https://github.com/openprovider/Openprovider-WHMCS-domains/issues/258

And this issue I am also currently experiencing: https://github.com/openprovider/Openprovider-WHMCS-domains/issues/240

**To Reproduce**
1. Have a domain with OpenProvider that requires renewal
2. Try to renew.
3. See error

**Expected behavior**
Domain should be renewed without further issues.

**Screenshots**
No need for a screenshot, here is the error:
```
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

For additional assistance, please reference the WHMCS TroubleShooting Guide »

TypeError: array_key_exists(): Argument #2 ($array) must be of type array, bool given in /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Hook/Manager.php:0
Stack trace:
#0 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Hook/Manager.php(0): array_key_exists()
#1 /var/www/sites/proj1ty4/public_html/prod/vendor/illuminate/support/Facades/Facade.php(261): WHMCS\Hook\Manager->processResults()
#2 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): Illuminate\Support\Facades\Facade::__callStatic()
#3 /var/www/sites/proj1ty4/public_html/prod/includes/registrarfunctions.php(0): WHMCS\Module\Registrar->call()
#4 /var/www/sites/proj1ty4/public_html/prod/op/clientsdomains.php(0): RegRenewDomain()
#5 {main}
```

**Server info:**
 - Distro: AlmaLinux 9
 - PHP: PHP 8.1
 - Web server: httpd

**Additional context**
Not only the domains ARE NOT RENEWED (I have one customer in particular that unfortunately trying to renew the domain via customer area paid domain renewals until 2026, because the domain never gets renewed), and if you renew them manually via OpenProvider Control Panel, the DOMAIN STATUS and DATES **ARE NOT UPDATED**.

**Comment by spylex** [comment]
I just missed 2 domain renewals and had to restore because the plugin just won't sync or renew.

**Comment by maverick85** [comment]
Two weeks flew by... and nothing.
I strongly believe this company should do an internal review on processes and organization. It's inadmissible that any fix takes weeks on end.

**Comment by sapillai** [comment]
Hi @maverick85 & @spylex,

We are extremely sorry for the situation. Development team has already been notified about the issue and is working to resolve it.

Regards,
Openprovider Support Team

**Comment by coriaweb** [comment]
I have the same error.

Is it possible that having been reported on March 6 it is still uncorrected?

**Comment by DigiNL** [comment]
The 'team' seems to have a long vacation as NOTHING happens with this AND other issues, bad bad bad

**Comment by sapillai** [comment]
Dear valued customers,

We would like to sincerely apologize for the delay in the release of the module with the promised bug fixes. We understand that you have been eagerly anticipating the updates, and we deeply regret any inconvenience that this delay may have caused.

We wish to inform you that despite our best efforts to address the list of bugs and improvements last week, we encountered a few unexpected issues during the testing phase, which prompted us to halt the release of the module as it required additional time and resources to resolve. We assure you that our team is working diligently to address these issues and we hope to deliver an improved version of the module very soon.

We understand how important it is for you to have a reliable and efficient module, and we assure you that our team is doing everything in their power to ensure that the module meets your expectations. We will keep you updated on the progress and notify you as soon as the new version is ready for use.

Once again, please accept our sincerest apologies for any inconvenience caused by this delay.

**Comment by andaga87** [comment]
I have speak today with OpenProvider team and the new module with all the bugs fixes will not come soon! This is the response:

We keep working and developing whmcs module, we already deployed 2 big updates, the current one is delayed. However we keep improving it, no ETA tho.

It's very stressfull for us too! I don't understand how this module is not updated quickly! You are maybe on the most Domains Provider and a big part of your customer work with this module! You put us in a bad situation!

We need developp our own module?

**Comment by ikke-zelf** [comment]
In the meantime i'm looking at [Netim](https://www.netim.com/) as a replacement.
No subscription fee needed, NL domains can be discounted if asked.
easy integration, and for all a fast responsive helpdesk.

**Comment by Kyzoe** [comment]
I am also looking at netim but it worries me that their website is allready down for more then 1 hr.

**Comment by coriaweb** [comment]
We are migrating to another provider, we already have almost 70 domains moved, it is a complex process, but this is not viable.

Openprovider has gone down a lot since I met them.

**Comment by ikke-zelf** [comment]
Where are you moving to?

**Comment by DAThosting** [comment]
News from OP (In Dashboard News):

`We are currently working on updating our WHMCS module, so it will be working with PHP 8.1 and with the latest version of WHMCS. ETA for this will be 2 weeks.` - 23.05.2023

Hope they get it runnning :)

**Comment by andaga87** [comment]
Personnaly I was totally satisfy with OP but now I was very angry with this module! We have moved all our hundreds of domains to RealtimeRegister!

The support of RealtimeRegister is just totally incredible and the module work perfectly well!

And there is an import automatic tool for moving all domains from OP to them!

Sorry for OP but on this case you have done a big error without updating this module.

**Comment by AndyAlvarezDev** [comment]
On the one hand, I agree that there should be efficient support and a completely updated module, but honestly, I don't believe that they can't develop this, rather, they're not interested. Perhaps their goal itself is for people who connect to Openprovider via WHMCS to withdraw from the system...

The subscription system they manage isn't profitable for them, but that doesn't mean they aren't capable. To be an authorized registrar by IANA, a lot of infrastructure and money is needed... The same developers who keep the services running, the API, and all the technology behind it, could clearly fix this in a few hours...

But the real question is, why doesn't anyone fix the module themselves? How can they enter the hosting and domain market without having a minimum understanding of programming? It's like selling fruits but not knowing what I'm selling!... Pay a developer to fix this module for you and that's it, I think the prices are too good to let it go just for not keeping the module updated.

**Comment by sapillai** [comment]
Hi All,

Greetings from Openprovider!

Please accept our sincere apologies for any inconvenience caused and the delay with the release of the updated version of the module. As some of you may have noticed already, we released two updated versions of the module with support for PHP 8.1, many bug fixes and improvements in the last 4-5 weeks. Our diligent team has taken into account the valuable feedback received from our users regarding the previous beta release, and as a result, we have implemented additional changes and improvements to effectively address the reported issues.

To facilitate broader testing and gather feedback, we have published the new version on GitHub as a pre-release. You are encouraged to download and explore this version, as it includes comprehensive fixes for all PHP 8.1 issues, improved renew logic, enhanced error reporting, etc. The pre-release can be accessed via the following link.
 
https://github.com/openprovider/Openprovider-WHMCS-domains/releases/tag/5.7.0-beta2 
 
We value your insights and input during this crucial testing phase, as they will contribute to the stability and reliability of the module. Your feedback will assist us in refining the module and ensuring its seamless integration with PHP 8.1 and the latest WHMCS version.
 
Once again, we extend our heartfelt appreciation for your collaboration and assistance. Thank you for choosing Openprovider!
 
**Note**: Testing on a live environment is not recommended as this is a beta version.

**Comment by AndyAlvarezDev** [comment]
"Really, @sapillai? You say you have implemented changes and improvements...

1) I don't see any implementations.
2) Code modifications, yes.

And I think any Dev who analyses the branches of the project would say that it's a shame. Since February, they modify a few lines of code and add unnecessary line breaks and then they go back and undo the changes...

What an "ironic" way to work... This generates a very bad reputation for the company.

Corrections should be from one day to another, at most 2-3 days, and after months they announce a "beta" version. They don't even have a production version?

In the last commit you made https://github.com/openprovider/Openprovider-WHMCS-domains/commit/2a36b39d9544bf17e59eb65feb0103301b00dfc6, with all due respect, is that what you call an update?

The code was:

`$call['args'] = array_map([$this, 'flattenArguments'], $call['args']);`

And you've added:

`$call['args'] = array_map([$this, 'flattenArguments'], (array)$call['args']);`

It's irrelevant to perform the conversion to array `(array)$call['args']`, the reason for this is that $call['args'] is already an array...

In the context of a stack trace, which is what `getTrace()` returns, each element in the array represents a call in the call stack, each of these elements is an array itself that includes different details about the call... 

One of these details is 'args', which is an array of arguments passed to the function in that call, therefore, 'args' will always be an array. There are many errors at first glance, take a deeper look, this is not an update!

If you really don't have anyone who can develop a good module, for 50 dollars an hour i can restructure the module in its entirety (10-15 hours) of total work. If you don't accept this offer, it's because there's no interest at all in fixing this!"

**Comment by sapillai** [comment]
Hi @AndyAlvarezDev 

Thank you for your feedback and for your offer to restructure the module. We appreciate your willingness to assist with this task. Your proposal has been shared with our product manager, who will carefully evaluate the options available for addressing the issue. We value your input, and if there's a possibility for collaboration, we will certainly reach out to discuss the details further.

Once again, thank you for your interest and the time you've taken to present this opportunity to us.

**Comment by pmjcreations** [comment]
When are you planning to fix all the PHP8x-related issues and release the production-ready, aka bug-free version of your plugin?

**Comment by D0ublek1ll** [comment]
> When are you planning to fix all the PHP8x-related issues and release the production-ready, aka bug-free version of your plugin?

I second this motion.

I've been stuck with a workflow that requires hand-on intervention for all domains we have registered trough open provider. This often fails because the rest of our business is fully automated. It is balooning costs.

We have actually started the process of slowly transfering out every domain that needs manual renewal at open provider. So if they wait too long with fixing this (aka, 9 more months or more) we will have no domains left with them. Their loss really.

Since automatic renewal or registration does not work in the latest module version, they are just slowly losing us as a customer.

**Comment by NTaravati** [comment]
After upgrading to phpv8.1, we missed 7 transfers. Restoring them costs 13€ each. This is an absolute mess.  Please fix this issue a.s.a.p.

**Comment by maxihoster** [comment]
I have hire an expert company developping a lot of WHMCS module and they ask me to fix and update correctly the module of OpenProvider for less than 200$.

I have accepted the quote and the module will be available until 1 week!

I don't understand OpenProvider company about this! If you don't want publish module for your system and want other does this.... You can only said us directly the true....

**Comment by spylex** [comment]
@maxihoster how did that work out for you? Any advice or something you can share?

**Comment by phamhung77** [comment]
Installed the latest release, and I am facing the same bug here.

**Comment by ikke-zelf** [comment]
I just moved away to MDR (my domain reseller)

**Comment by pmjcreations** [comment]
Hi @sapillai,

I see that you have changed the readme two weeks ago to

> We are actively working on updating the module and hope to release a new version soon that is compatible with **PHP 8** and newer WHMCS versions. Meanwhile, pull requests will be reviewed, and potentially merged.

I'm happy to see this improvement, and I can now almost stop looking for another alternative.  

I wish to make things a bit clear here: WHMCS never offered support for PHP 8; they currently support PHP 8.1, and they mentioned that 

> PHP 8.2 support is something we are working on and aim to deliver in the first half of 2024

So, I request you to start working on PHP 8.2 or 8.1 as the supported version if the community and users agree/are interested in it.

**Comment by pmjcreations** [comment]
I see version 5.8.0 is now released, and the module is compatible with WHMCS versions up to 8.10.1 and PHP 8.1

**Comment by sapillai** [comment]
Hi,

Domain renewal issues have been fixed in the latest release - [version 5.8.0](https://github.com/openprovider/Openprovider-WHMCS-domains/releases/tag/v5.8.0) and it is compatible with PHP 8.1.

> So, I request you to start working on PHP 8.2 or 8.1 as the supported version if the community and users agree/are interested in it.

@pmjcreations we already have a task for making the module compatible with PHP 8.2 and our team is working on it.
