### ISSUE TITLE
[BUG] v5.7.0 BETA

### ISSUE THREAD

**Issue by subedinfo** [openprovider/Openprovider-WHMCS-domains#276]
**Describe the bug**
When on:

- Admin Panel > Clients > Domain Registrations > <select desired OP domain>
- Admin Panel > Enter a Client Profile > Domains > <select desired OP domain>

It crashes with the error:
```
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

For additional assistance, please reference the WHMCS TroubleShooting Guide »

TypeError: Cannot access offset of type string on string in /var/www/projects/lk78nht/public_html/whmcs/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Domain/AdditionalFields.php:96
Stack trace:
#0 /var/www/projects/lk78nht/public_html/whmcs/modules/registrars/openprovider/src/AdditionalFields.php(93): WeDevelopCoffee\wPower\Domain\AdditionalFields->getFilteredAdditionalFields()
#1 /var/www/projects/lk78nht/public_html/whmcs/modules/registrars/openprovider/helpers.php(18): OpenProvider\WhmcsRegistrar\src\AdditionalFields->get()
#2 /var/www/projects/lk78nht/public_html/whmcs/resources/domains/additionalfields.php(8): openprovider_additional_fields()
#3 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains/AdditionalFields.php(0): unknown()
#4 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains/AdditionalFields.php(0): WHMCS\Domains\AdditionalFields->fetch()
#5 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains/AdditionalFields.php(0): WHMCS\Domains\AdditionalFields->loadFieldsData()
#6 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains/AdditionalFields.php(0): WHMCS\Domains\AdditionalFields->setTLD()
#7 /var/www/projects/lk78nht/public_html/whmcs/op/clientsdomains.php(0): WHMCS\Domains\AdditionalFields->setDomain()
#8 {main}
```

**To Reproduce**
Described above two methods to reach the error

**Expected behavior**
See domain information

**Server info:**
 - Distro: AlmaLinux 9.2
 - PHP: 8.1
 - Web server: httpd/Apache

**Additional context**

Seems like the old error when removing additionalfields.php fixed the problem. You've come up with a solution to this in the past.

**Comment by subedinfo** [comment]
@sapillai provided a fix which we tested with success and will be merged.
