### ISSUE TITLE
[BUG] 5.7.0-beta on Admin homepage

### ISSUE THREAD

**Issue by VORD-Sven** [openprovider/Openprovider-WHMCS-domains#277]
```
Oops!
Something went wrong and we couldn't process your request.

Please go back to the previous page and try again.

For additional assistance, please reference the WHMCS TroubleShooting Guide »

TypeError: array_map(): Argument #2 ($array) must be of type array, null given in /home/sites/<-REDACTED->/public_html/my/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/InvalidTag.php:89
Stack trace:
#0 /home/sites/<-REDACTED->/public_html/my/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/InvalidTag.php(89): array_map(Array, NULL)
#1 [internal function]: phpDocumentor\Reflection\DocBlock\Tags\InvalidTag->phpDocumentor\Reflection\DocBlock\Tags\{closure}(Array)
#2 /home/sites/<-REDACTED->/public_html/my/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/InvalidTag.php(93): array_map(Object(Closure), Array)
#3 /home/sites/<-REDACTED->/public_html/my/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/InvalidTag.php(66): phpDocumentor\Reflection\DocBlock\Tags\InvalidTag->flattenExceptionBacktrace(Object(InvalidArgumentException))
#4 /home/sites/<-REDACTED->/public_html/my/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(220): phpDocumentor\Reflection\DocBlock\Tags\InvalidTag->withError(Object(InvalidArgumentException))
#5 /home/sites/<-REDACTED->/public_html/my/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(148): phpDocumentor\Reflection\DocBlock\StandardTagFactory->createTag('\\Openprovider\\A...', 'throws', Object(phpDocumentor\Reflection\Types\Context))
#6 /home/sites/<-REDACTED->/public_html/my/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php(244): phpDocumentor\Reflection\DocBlock\StandardTagFactory->create('@throws \\Openpr...', Object(phpDocumentor\Reflection\Types\Context))
#7 /home/sites/<-REDACTED->/public_html/my/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php(104): phpDocumentor\Reflection\DocBlockFactory->parseTagBlock('@param bool $w...', Object(phpDocumentor\Reflection\Types\Context))
#8 /home/sites/<-REDACTED->/public_html/my/modules/registrars/openprovider/OpenProvider/API/ParamsCreator.php(194): phpDocumentor\Reflection\DocBlockFactory->create('/**\n * Oper...')
#9 /home/sites/<-REDACTED->/public_html/my/modules/registrars/openprovider/OpenProvider/API/ParamsCreator.php(64): OpenProvider\API\ParamsCreator->getMethodParamsTypes(Object(ReflectionMethod))
#10 /home/sites/<-REDACTED->/public_html/my/modules/registrars/openprovider/OpenProvider/API/ParamsCreator.php(40): OpenProvider\API\ParamsCreator->createParametersGetDelete(Array, Object(Openprovider\Api\Rest\Client\Person\Api\ResellerServiceApi), 'getReseller')
#11 /home/sites/<-REDACTED->/public_html/my/modules/registrars/openprovider/OpenProvider/API/ApiV1.php(107): OpenProvider\API\ParamsCreator->createParameters(Array, Object(Openprovider\Api\Rest\Client\Person\Api\ResellerServiceApi), 'getReseller')
#12 /home/sites/<-REDACTED->/public_html/my/modules/registrars/openprovider/OpenProvider/API/ApiHelper.php(512): OpenProvider\API\ApiV1->call('retrieveReselle...', Array)
#13 /home/sites/<-REDACTED->/public_html/my/modules/registrars/openprovider/Controllers/Hooks/Widgets/BalanceWidget.php(40): OpenProvider\API\ApiHelper->getReseller()
#14 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Module/AbstractWidget.php(0): OpenProvider\WhmcsRegistrar\Controllers\Hooks\Widgets\BalanceWidget->getData()
#15 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Module/AbstractWidget.php(0): WHMCS\Module\AbstractWidget->fetchData(false)
#16 /home/sites/<-REDACTED->/public_html/my/templates_c/2271f5dbe082284df0435e567fd9f99b57178b36_0.file.homepage.tpl.php(145): WHMCS\Module\AbstractWidget->render()
#17 /home/sites/<-REDACTED->/public_html/my/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_64848c32281ac3_84985157(Object(Smarty_Internal_Template))
#18 /home/sites/<-REDACTED->/public_html/my/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#19 /home/sites/<-REDACTED->/public_html/my/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#20 /home/sites/<-REDACTED->/public_html/my/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 0)
#21 /home/sites/<-REDACTED->/public_html/my/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 0)
#22 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Smarty.php(0): Smarty_Internal_TemplateBase->fetch('blend/homepage....', NULL, NULL, NULL, false, true, false)
#23 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Admin.php(0): WHMCS\Smarty->fetch('blend/homepage....')
#24 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Admin.php(0): WHMCS\Admin->output()
#25 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Admin/Controller/HomepageController.php(0): WHMCS\Admin->display()
#26 [internal function]: WHMCS\Admin\Controller\HomepageController->index(Object(WHMCS\Http\Message\ServerRequest))
#27 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/CallableHandler.php(26): call_user_func_array(Array, Array)
#28 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/fast-route/src/FastRoute.php(96): Middlewares\Utils\CallableHandler::execute(Array, Array)
#29 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/HandleProcessor.php(0): Middlewares\FastRoute->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#30 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\HandleProcessor->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#31 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\HandleProcessor->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#32 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#33 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#34 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#35 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Admin\ApplicationSupport\Route\Middleware\Assent->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#36 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#37 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#38 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#39 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Security/Middleware/Authorization.php(0): WHMCS\Security\Middleware\Authorization->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#40 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/AbstractProxyMiddleware.php(0): WHMCS\Security\Middleware\Authorization->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#41 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\AbstractProxyMiddleware->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#42 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\AbstractProxyMiddleware->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#43 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#44 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#45 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#46 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/AbstractProxyMiddleware.php(0): WHMCS\Admin\ApplicationSupport\Route\Middleware\Authentication->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#47 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\AbstractProxyMiddleware->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#48 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\AbstractProxyMiddleware->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#49 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#50 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#51 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#52 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Admin\ApplicationSupport\Route\Middleware\DirectoryValidation->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#53 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#54 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#55 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendPsr7Response.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#56 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendPsr7Response.php(0): unknown()
#57 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendPsr7Response.php(0): WHMCS\Route\Middleware\BackendPsr7Response->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#58 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\BackendPsr7Response->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#59 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#60 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#61 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Dispatcher.php(56): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#62 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendDispatch.php(0): Middlewares\Utils\Dispatcher->dispatch(Object(WHMCS\Http\Message\ServerRequest))
#63 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\BackendDispatch->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#64 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\BackendDispatch->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#65 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#66 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#67 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutePathMatch.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#68 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutePathMatch->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#69 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutePathMatch->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#70 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#71 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#72 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/WhitelistFilter.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#73 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): WHMCS\Route\Middleware\WhitelistFilter->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#74 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\WhitelistFilter->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#75 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#76 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#77 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableClientModuleRequest.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#78 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableClientModuleRequest->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#79 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableClientModuleRequest->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#80 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#81 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#82 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableAdminRequestUri.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#83 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableAdminRequestUri->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#84 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableAdminRequestUri->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#85 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#86 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#87 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableRequestUri.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#88 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableRequestUri.php(0): unknown()
#89 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableRequestUri->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#90 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableRequestUri->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#91 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#92 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#93 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableRequestQueryUri.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#94 /home/sites/<-REDACTED->/public_html/my/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableRequestQueryUri->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#95 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableRequestQueryUri->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate))
#96 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest))
#97 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest))
#98 /home/sites/<-REDACTED->/public_html/my/vendor/middlewares/utils/src/Dispatcher.php(56): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest))
#99 /home/sites/<-REDACTED->/public_html/my/admin/index.php(0): Middlewares\Utils\Dispatcher->dispatch(Object(WHMCS\Http\Message\ServerRequest))
#100 {main}
``` 

**To Reproduce**
main admin dashboard "default install dir = /admin"

**Expected behavior**
admin dashboard. 

i can access other pages like the configgeneral.php from there i can navigate to client accounts and products just fine it just the admin dashboard.

**Server info:**
 - Distro: Centos
 - PHP: 8.1.17
 - Web server: FPM/FastCGI

**Comment by sapillai** [comment]
Hi @VORD-Sven,

Thank you for testing the beta version and sharing feedback. The issue has been reported to our WHMCS team.

**Comment by sapillai** [comment]
Hi @VORD-Sven,

We have released a new version of the module with additional bug fixes and further improvements. You can download the pre-release from: [here](https://github.com/openprovider/Openprovider-WHMCS-domains/archive/refs/tags/5.7.0-beta2.zip)

Would you be able to test the updated version to see if the problem persists? If the problem persists, please try replacing file '**modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/InvalidTag.php**' with the attached version - [InvalidTag.zip](https://github.com/openprovider/Openprovider-WHMCS-domains/files/12023564/InvalidTag.zip)

**Comment by kondryukwph** [comment]
Same error with Openprovider module 5.8.0 , WHMCS 8.12.1 , PHP 8.1
After replacing with attached version - [InvalidTag.zip](https://github.com/openprovider/Openprovider-WHMCS-domains/files/12023564/InvalidTag.zip) - error fixed
