### ISSUE TITLE
[BUG] 5.7.0-beta - Error when adding domain to product

### ISSUE THREAD

**Issue by subedinfo** [openprovider/Openprovider-WHMCS-domains#278]
**Describe the bug**
When purchasing a service which requires domain, the site gets frozen looking for domain and doesn't let move forward.
Captured PHP errors.

**To Reproduce**
1. Go to a hosting package that requires a domain
2. Test done using  the option "I will use my own domain and update name servers"
3. Insert domain name
4. Verifying indefinitely

**Expected behavior**
Domain verified.

**Error**
```
==> /var/log/php-fpm/www-error.log <==
[16-Jun-2023 11:03:21 Europe/Lisbon] [WHMCS Application] ERROR: Error: Class "OpenproviderPremiumDns\OpenproviderPremiumDnsModuleHelper" not found in /var/www/projects/lk78nht/public_html/whmcs/modules/servers/openproviderpremiumdns/hooks.php:26
 Stack trace:
  #0 [internal function]: WHMCS\Utility\SafeInclude::{closure}()
  #1 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Hook/Manager.php(0): call_user_func()
  #2 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Hook/Manager.php(0): WHMCS\Hook\Manager->run()
  #3 /var/www/projects/lk78nht/public_html/whmcs/vendor/illuminate/support/Facades/Facade.php(261): WHMCS\Hook\Manager->validate()
  #4 /var/www/projects/lk78nht/public_html/whmcs/includes/functions.php(0): Illuminate\Support\Facades\Facade::__callStatic()
  #5 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains/DomainLookup/Provider/AbstractProvider.php(0): run_validate_hook()
  #6 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Domain/Checker.php(0): WHMCS\Domains\DomainLookup\Provider\AbstractProvider->checkOwnDomain()
  #7 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Domain/Checker.php(0): WHMCS\Domain\Checker->checkOwndomain()
  #8 [internal function]: WHMCS\Domain\Checker->ajaxCheck()
  #9 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/CallableHandler.php(26): call_user_func_array()
  #10 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/fast-route/src/FastRoute.php(96): Middlewares\Utils\CallableHandler::execute()
  #11 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/HandleProcessor.php(0): Middlewares\FastRoute->process()
  #12 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\HandleProcessor->_process()
  #13 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\HandleProcessor->process()
  #14 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
  #15 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
  #16 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/AbstractProxyMiddleware.php(0): Middlewares\Utils\Delegate->process()
  #17 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\AbstractProxyMiddleware->_process()
  #18 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\AbstractProxyMiddleware->process()
  #19 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
  #20 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
  #21 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/AbstractProxyMiddleware.php(0): Middlewares\Utils\Delegate->process()
  #22 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\AbstractProxyMiddleware->_process()
  #23 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\AbstractProxyMiddleware->process()
  #24 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
  #25 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
  #26 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendPsr7Response.php(0): Middlewares\Utils\Delegate->process()
  #27 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendPsr7Response.php(0): unknown()
  #28 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendPsr7Response.php(0): WHMCS\Route\Middleware\BackendPsr7Response->_process()
  #29 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\BackendPsr7Response->process()
  #30 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
  #31 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
  #32 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Dispatcher.php(56): Middlewares\Utils\Delegate->process()
  #33 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendDispatch.php(0): Middlewares\Utils\Dispatcher->dispatch()
  #34 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\BackendDispatch->_process()
  #35 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\BackendDispatch->process()
  #36 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
  #37 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
  #38 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutePathMatch.php(0): Middlewares\Utils\Delegate->process()
  #39 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutePathMatch->_process()
  #40 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutePathMatch->process()
  #41 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
  #42 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
  #43 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/WhitelistFilter.php(0): Middlewares\Utils\Delegate->process()
  #44 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): WHMCS\Route\Middleware\WhitelistFilter->_process()
  #45 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\WhitelistFilter->process()
  #46 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
  #47 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
  #48 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableClientModuleRequest.php(0): Middlewares\Utils\Delegate->process()
  #49 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableClientModuleRequest->_process()
  #50 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableClientModuleRequest->process()
  #51 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
  #52 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
  #53 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableAdminRequestUri.php(0): Middlewares\Utils\Delegate->process()
  #54 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableAdminRequestUri->_process()
  #55 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableAdminRequestUri->process()
  #56 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
  #57 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
  #58 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableRequestUri.php(0): Middlewares\Utils\Delegate->process()
  #59 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableRequestUri.php(0): unknown()
  #60 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableRequestUri->_process()
  #61 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableRequestUri->process()
  #62 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
  #63 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
  #64 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableRequestQueryUri.php(0): Middlewares\Utils\Delegate->process()
  #65 /var/www/projects/lk78nht/public_html/whmcs/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableRequestQueryUri->_process()
  #66 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableRequestQueryUri->process()
  #67 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
  #68 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
  #69 /var/www/projects/lk78nht/public_html/whmcs/vendor/middlewares/utils/src/Dispatcher.php(56): Middlewares\Utils\Delegate->process()
  #70 /var/www/projects/lk78nht/public_html/whmcs/index.php(0): Middlewares\Utils\Dispatcher->dispatch()
  #71 {main} {"exception":"[object] (Error(code: 0): Class \"OpenproviderPremiumDns\\OpenproviderPremiumDnsModuleHelper\" not found at /var/www/projects/lk78nht/public_html/whmcs/modules/servers/openproviderpremiumdns/hooks.php:26)"} []
```

**Server info:**
 - Distro: PRETTY_NAME="AlmaLinux 9.2 (Turquoise Kodkod)"
 - PHP 8.1.19 (fpm-fcgi) (built: May 10 2023 13:43:03)
 - Web server: Server version: Apache/2.4.53 (AlmaLinux)

**Additional context**
It seems to be a conflict with [OpenProvider's Premium DNS module](https://github.com/openprovider/openprovider-whmcs-premiumDNS/)

**THIS ERROR DOES NOT SHOW IF YOU GO TO REGULAR > REGISTER NEW DOMAIN**

**Comment by sapillai** [comment]
Hi @subedinfo,

Sorry to know that you are having issue with purchasing a service which requires domain name.
 
The error is caused by the Premium DNS module and unfortunately, we had to pause the development of the module. We have already updated this information (unmaintained) in the GitHub repo: [openprovider-whmcs-premiumDNS](https://github.com/openprovider/openprovider-whmcs-premiumDNS) and we don't recommend using the Premium DNS module until it is updated. We plan to resume the development of the module in the future, but we don't have an ETA at this point. You can watch the repo for updates(Click on the **Watch** >> **Custom** >> Check the '**Releases**' box and click on **Apply**).

Please deactivate or remove the Premium DNS module to resolve the issue.
