### ISSUE TITLE
[BUG] 5.8.0 - Registrar TLD Sync

### ISSUE THREAD

**Issue by maverick85** [openprovider/Openprovider-WHMCS-domains#318]
**Describe the bug**
After updating the module we proceeded to the Utility Registrar TLD Sync.
This immediately triggers a PHP Fatal Error.

**To Reproduce**
1. Go to Admin Panel
2. Click on Utilities
3. Scroll down to Registrar TLD Sync

**Expected behavior**
A selection box should be displayed to select the OpenProvider option

**Server info:**
 - Distro: AlmaLinux 9.4
 - PHP: 8.1.28
 - Web server: httpd

**Error:**

SHORT VERSION:
```
$ sudo -u apache php -d max_execution_time=0 /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/cron/DownloadTldPrices.php
[WHMCS Application] ERROR: Error: Class "OpenProvider\WhmcsRegistrar\src\Configuration" not found in /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/init.php:57 Stack trace: #0 /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/cron/DownloadTldPrices.php(11): openprovider_bind_required_classes() #1 {main} {"exception":"[object] (Error(code: 0): Class \"OpenProvider\\WhmcsRegistrar\\src\\Configuration\" not found at /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/init.php:57)"} []
Error: Class "OpenProvider\WhmcsRegistrar\src\Configuration" not found in /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/init.php:57

#0 /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/cron/DownloadTldPrices.php(11): openprovider_bind_required_classes()
```

LONG VERSION:
```
Error: Class "OpenProvider\WhmcsRegistrar\src\Configuration" not found in /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/openprovider.php:383
Stack trace:
#0 /var/www/sites/proj1ty4/public_html/prod/modules/registrars/openprovider/openprovider.php(41): openprovider_registrar_launch_decorator()
#1 [internal function]: openprovider_getConfigArray()
#2 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func()
#3 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call()
#4 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\Registrar->call()
#5 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Admin/Utilities/Tools/TldSync/TldSyncController.php(0): WHMCS\Module\Registrar->getDisplayName()
#6 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Admin/Utilities/Tools/TldSync/TldSyncController.php(0): unknown()
#7 [internal function]: WHMCS\Admin\Utilities\Tools\TldSync\TldSyncController->importStart()
#8 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/CallableHandler.php(26): call_user_func_array()
#9 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/fast-route/src/FastRoute.php(96): Middlewares\Utils\CallableHandler::execute()
#10 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/HandleProcessor.php(0): Middlewares\FastRoute->process()
#11 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\HandleProcessor->_process()
#12 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\HandleProcessor->process()
#13 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
#14 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
#15 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process()
#16 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Admin\ApplicationSupport\Route\Middleware\Assent->process()
#17 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
#18 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
#19 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process()
#20 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Security/Middleware/Authorization.php(0): WHMCS\Security\Middleware\Authorization->process()
#21 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/AbstractProxyMiddleware.php(0): WHMCS\Security\Middleware\Authorization->process()
#22 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\AbstractProxyMiddleware->_process()
#23 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\AbstractProxyMiddleware->process()
#24 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
#25 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
#26 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process()
#27 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/AbstractProxyMiddleware.php(0): WHMCS\Admin\ApplicationSupport\Route\Middleware\Authentication->process()
#28 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\AbstractProxyMiddleware->_process()
#29 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\AbstractProxyMiddleware->process()
#30 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
#31 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
#32 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process()
#33 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Admin\ApplicationSupport\Route\Middleware\DirectoryValidation->process()
#34 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
#35 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
#36 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendPsr7Response.php(0): Middlewares\Utils\Delegate->process()
#37 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendPsr7Response.php(0): WHMCS\Route\Middleware\BackendPsr7Response->_process()
#38 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\BackendPsr7Response->process()
#39 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
#40 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
#41 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Dispatcher.php(56): Middlewares\Utils\Delegate->process()
#42 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendDispatch.php(0): Middlewares\Utils\Dispatcher->dispatch()
#43 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\BackendDispatch->_process()
#44 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\BackendDispatch->process()
#45 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
#46 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
#47 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutePathMatch.php(0): Middlewares\Utils\Delegate->process()
#48 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutePathMatch->_process()
#49 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutePathMatch->process()
#50 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
#51 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
#52 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/WhitelistFilter.php(0): Middlewares\Utils\Delegate->process()
#53 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): WHMCS\Route\Middleware\WhitelistFilter->_process()
#54 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\WhitelistFilter->process()
#55 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
#56 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
#57 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableClientModuleRequest.php(0): Middlewares\Utils\Delegate->process()
#58 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableClientModuleRequest->_process()
#59 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableClientModuleRequest->process()
#60 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
#61 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
#62 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableAdminRequestUri.php(0): Middlewares\Utils\Delegate->process()
#63 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableAdminRequestUri->_process()
#64 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableAdminRequestUri->process()
#65 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
#66 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
#67 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableRequestUri.php(0): Middlewares\Utils\Delegate->process()
#68 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableRequestUri->_process()
#69 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableRequestUri->process()
#70 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
#71 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
#72 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableRequestQueryUri.php(0): Middlewares\Utils\Delegate->process()
#73 /var/www/sites/proj1ty4/public_html/prod/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableRequestQueryUri->_process()
#74 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableRequestQueryUri->process()
#75 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}()
#76 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Delegate.php(31): call_user_func()
#77 /var/www/sites/proj1ty4/public_html/prod/vendor/middlewares/utils/src/Dispatcher.php(56): Middlewares\Utils\Delegate->process()
#78 /var/www/sites/proj1ty4/public_html/prod/index.php(0): Middlewares\Utils\Dispatcher->dispatch()
#79 {main}
```

**Comment by maverick85** [comment]
UPDATE: We repeated the update process. After re-doing it, this error went away.
