### ISSUE TITLE
[BUG] Exceptions when using WHMCS' internal API

### ISSUE THREAD

**Issue by DennisSkov** [openprovider/Openprovider-WHMCS-domains#355]
**Describe the bug**
We sometimes rely on being able to use the WHMCS API to perform domain operations.
If we're calling DomainRenew, we're seeing the following error:
```
TypeError: array_map(): Argument #2 ($array) must be of type array, null given in /home/username/dev.domain.com/client/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/InvalidTag.php:89
Stack trace:
#0 /home/username/dev.domain.com/client/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/InvalidTag.php(89): array_map(Array, NULL)
#1 [internal function]: phpDocumentor\Reflection\DocBlock\Tags\InvalidTag->phpDocumentor\Reflection\DocBlock\Tags\{closure}(Array)
#2 /home/username/dev.domain.com/client/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/InvalidTag.php(93): array_map(Object(Closure), Array)
#3 /home/username/dev.domain.com/client/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/InvalidTag.php(66): phpDocumentor\Reflection\DocBlock\Tags\InvalidTag->flattenExceptionBacktrace(Object(InvalidArgumentException))
#4 /home/username/dev.domain.com/client/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(220): phpDocumentor\Reflection\DocBlock\Tags\InvalidTag->withError(Object(InvalidArgumentException))
#5 /home/username/dev.domain.com/client/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(148): phpDocumentor\Reflection\DocBlock\StandardTagFactory->createTag('\\Openprovider\\A...', 'throws', Object(phpDocumentor\Reflection\Types\Context))
#6 /home/username/dev.domain.com/client/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php(244): phpDocumentor\Reflection\DocBlock\StandardTagFactory->create('@throws \\Openpr...', Object(phpDocumentor\Reflection\Types\Context))
#7 /home/username/dev.domain.com/client/modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php(104): phpDocumentor\Reflection\DocBlockFactory->parseTagBlock('@param string ...', Object(phpDocumentor\Reflection\Types\Context))
#8 /home/username/dev.domain.com/client/modules/registrars/openprovider/OpenProvider/API/ParamsCreator.php(194): phpDocumentor\Reflection\DocBlockFactory->create('/**\n * Oper...')
#9 /home/username/dev.domain.com/client/modules/registrars/openprovider/OpenProvider/API/ParamsCreator.php(64): OpenProvider\API\ParamsCreator->getMethodParamsTypes(Object(ReflectionMethod))
#10 /home/username/dev.domain.com/client/modules/registrars/openprovider/OpenProvider/API/ParamsCreator.php(40): OpenProvider\API\ParamsCreator->createParametersGetDelete(Array, Object(Openprovider\Api\Rest\Client\Domain\Api\DomainServiceApi), 'listDomains')
#11 /home/username/dev.domain.com/client/modules/registrars/openprovider/OpenProvider/API/ApiV1.php(109): OpenProvider\API\ParamsCreator->createParameters(Array, Object(Openprovider\Api\Rest\Client\Domain\Api\DomainServiceApi), 'listDomains')
#12 /home/username/dev.domain.com/client/modules/registrars/openprovider/OpenProvider/API/ApiHelper.php(44): OpenProvider\API\ApiV1->call('searchDomainReq...', Array)
#13 /home/username/dev.domain.com/client/modules/registrars/openprovider/Controllers/System/RenewDomainController.php(50): OpenProvider\API\ApiHelper->getDomain(Object(OpenProvider\API\Domain))
#14 /home/username/dev.domain.com/client/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(47): OpenProvider\WhmcsRegistrar\Controllers\System\RenewDomainController->renew(Array)
#15 /home/username/dev.domain.com/client/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(54): WeDevelopCoffee\wPower\Core\Instance->execute('renew', Array)
#16 /home/username/dev.domain.com/client/modules/registrars/openprovider/openprovider.php(394): WeDevelopCoffee\wPower\Core\Launch->output(Array, 'renewDomain')
#17 /home/username/dev.domain.com/client/modules/registrars/openprovider/openprovider.php(190): openprovider_registrar_launch_decorator('renewDomain', Array)
#18 [internal function]: openprovider_RenewDomain(Array)
#19 /home/username/dev.domain.com/client/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func('openprovider_Re...', Array)
#20 /home/username/dev.domain.com/client/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call('RenewDomain', Array)
#21 /home/username/dev.domain.com/client/includes/registrarfunctions.php(0): WHMCS\Module\Registrar->call('RenewDomain')
#22 /home/username/dev.domain.com/client/includes/api/domainrenew.php(0): RegRenewDomain(Array)
#23 /home/username/dev.domain.com/client/vendor/whmcs/whmcs-foundation/lib/Api/V1/Api.php(0): unknown()
#24 /home/username/dev.domain.com/client/vendor/whmcs/whmcs-foundation/lib/Api/V1/Api.php(0): WHMCS\Api\V1\Api->executeApiCall()
#25 /home/username/dev.domain.com/client/includes/functions.php(0): WHMCS\Api\V1\Api->call()
#26 /home/username/dev.domain.com/client/test.php(11): localAPI('DomainRenew', Array)
#27 {main}
```

**To Reproduce**
1. Configure a domain with the OpenProvider registrar module
2. Use the "[DomainRenew](https://developers.whmcs.com/api-reference/domainrenew/)" API function to renew that domain
3. See error

**Expected behavior**
The API request should complete.

**Screenshots**

**Server info:**
 - Distro: CloudLinux 9
 - PHP: 8.1
 - Web server: LiteSpeed

**Comment by DennisSkov** [comment]
The same exception seems to be thrown when accessing the WHMCS dashboard. We're connecting to the sandbox environment on this installation, so that might be the problem.
It does not seem to be an issue on our production installation.

**Comment by sapillai** [comment]
Hi @DennisSkov,

Thank you for reporting the issue.

>If we're calling DomainRenew, we're seeing the following error:
 
Are you facing this issue when trying to renew any specific TLD in Sandbox or is it happening for all TLDs? Also, can you please check if Renew Registrar Command is working (**Client Profile** >> **Domains** tab >> **Renew** button under R**egistrar Commands**)? 

>This happens for multiple other methods, like _GetTldPricing(). I just confirmed that it only happens when using the sandbox environment.

The TLD Import & Pricing Sync in Sandbox environment has been fixed in the new beta release - https://github.com/openprovider/Openprovider-WHMCS-domains/releases/tag/v5.9.0-beta

**Comment by DennisSkov** [comment]
Hi.

I didn't see there was a beta release. Just installed it, and it fixed every issue so far.
The same exception was also thrown when accessing the dashboard.

I just remembered that we run _GetTldPricing on `PreRegistrarRenewDomain`, so that explains why we saw the exception when we tried to renew domains.

Case closed!
